### PR TITLE
Updated kernel to 3.11.0-19-generic

### PR DESCRIPTION
**Pull request by prologic**
This also moves version management of the kernle image to `vars/main.yml``

### CODE REVIEW

**Comment by kencochrane** [comment]
Thanks! I like your change, but I can't merge automatically can you fix the merge conflict and I'll merge it in.

**Comment by prologic** [comment]
SUre thing will do shrotly!

cheers
James

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by kencochrane** [comment]
Thank you. Sorry for the slow reply, the notification email got lost in
another email filter.

**Comment by prologic** [comment]
I'm guessing this PR is no longer needed as I took too long to rebase my commits? :)

**Comment by kencochrane** [comment]
@prologic I completely forgot about this one, sorry for the delay.

**Comment by prologic** [comment]
Me too!

**Pull request closed without merging**
